name: CI

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    types:
      - opened
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Run cargo fmt (check if all code is rustfmt-ed)
        run: cargo fmt --all -- --check
      - name: Run cargo clippy (deny warnings)
        run: cargo clippy -- -D warnings

  publish-check:
    name: Publish Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fetch
      - run: cargo publish --dry-run

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
      - lint
      - publish-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fetch
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
